apiVersion: apps/v1
kind: Deployment
metadata:
  name: starwars-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starwars-frontend
  template:
    metadata:
      labels:
        app: starwars-frontend
    spec:
      containers:
      - name: frontend
        image: starwars-project-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: starwars-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: starwars-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: 30000  # Expose on Minikube's external port
