apiVersion: apps/v1
kind: Deployment
metadata:
  name: starwars-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starwars-backend
  template:
    metadata:
      labels:
        app: starwars-backend
    spec:
      containers:
      - name: starwars-project-backend
        image: starwars-project-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: starwars-backend-service
spec:
  type: LoadBalancer
  selector:
    app: starwars-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
